<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <Include>[PRM.Application]*,[PRM.Api]*,[PRM.ConsoleClient]*,[PRM.Domain]*,[PRM.Infrastructure]*,[PRM.SharedKernel]*</Include>
    <Exclude>[PRM.Persistence]*,[PRM.Api]PRM.Api.Controllers.*,[PRM.Api]Program,[PRM.ConsoleClient]PRM.ConsoleClient.Views.*,[PRM.ConsoleClient]PRM.ConsoleClient.Menus.*,[PRM.ConsoleClient]PRM.ConsoleClient.Program</Exclude>
    <Threshold>60</Threshold>
    <ThresholdType>line</ThresholdType>
    <ThresholdStat>total</ThresholdStat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="7.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PRM.Api\PRM.Api.csproj" />
    <ProjectReference Include="..\..\src\PRM.ConsoleClient\PRM.ConsoleClient.csproj" />
    <ProjectReference Include="..\..\src\PRM.Domain\PRM.Domain.csproj" />
    <ProjectReference Include="..\..\src\PRM.Application\PRM.Application.csproj" />
    <ProjectReference Include="..\..\src\PRM.SharedKernel\PRM.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\PRM.Infrastructure\PRM.Infrastructure.csproj" />
  </ItemGroup>

</Project>
